name: ${project.name}
main: vg.civcraft.mc.civduties.CivDuties
version: ${project.version}
softdepend: [Mercury, BetterShards, Vault]
commands:
   duty:
      permission: civduties.*
permissions:
  civduties.*:
   default: op
