name: ${project.name}
main: vg.civcraft.mc.civduties.CivDuties
version: ${project.version}
depend: [CivModCore]
softdepend: [Vault]
commands:
   duty:
      permission: civduties.duty
permissions:
  civduties.duty:
   default: op
