name: CivDuties
main: vg.civcraft.mc.civduties.CivDuties
version: 1.5.0-SNAPSHOT
depend: [CivModCore]
softdepend: [Vault]
api-version: 1.16
commands:
   duty:
      permission: civduties.duty
permissions:
  civduties.duty:
   default: op
